version: '3.8'

services:
  portfolio:
    container_name: portfolio
    build: .
    env_file: .env
    restart: on-failure
    cpus: '0.5'
    mem_limit: 750M
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`amalfitano.me`)"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.routers.portfolio.middlewares=redirect@file"
      - "traefik.http.routers.portfolio-secured.rule=Host(`amalfitano.me`)"
      - "traefik.http.routers.portfolio-secured.entrypoints=web-secured"
      - "traefik.http.routers.portfolio-secured.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

  redis:
    container_name: redis
    image: redis:alpine
    restart: on-failure
    cpus: '0.5'
    mem_limit: 750M
    networks:
      - web
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  web:
    name: infrastructure_web
    external: true
