version: '3.8'

services:
  portfolio_website:
    container_name: portfolio_website
    build: 
      context: .
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 750M
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio_website.rule=Host(`amalfitano.me`)"
      - "traefik.http.routers.portfolio_website.entrypoints=web"
      - "traefik.http.routers.portfolio_website.middlewares=redirect@file"
      - "traefik.http.routers.portfolio_website-secured.rule=Host(`amalfitano.me`)"
      - "traefik.http.routers.portfolio_website-secured.entrypoints=web-secured"
      - "traefik.http.routers.portfolio_website-secured.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.portfolio_website.loadbalancer.server.port=80"

networks:
  web:
    name: infrastructure_web
    external: true
